name: GitHub Actions Demo 2
run-name: ${{ github.actor }} is testing
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '42 15 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }} event."
      - run: cp ./README.md ./test.md
